// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5915.MercyRobot2019.subsystems;


import org.usfirst.frc5915.MercyRobot2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class ArcadeDrive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private VictorSP leftFrontMotor;
    private VictorSP leftBackMotor;
    private SpeedControllerGroup leftMotors;
    private VictorSP rightFrontMotor;
    private VictorSP rightBackMotor;
    private SpeedControllerGroup rightMotors;
    public DifferentialDrive axium;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public ArcadeDrive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        leftFrontMotor = new VictorSP(2);
        addChild("Left Front Motor",leftFrontMotor);
        leftFrontMotor.setInverted(true);
        
        leftBackMotor = new VictorSP(3);
        addChild("Left Back Motor",leftBackMotor);
        leftBackMotor.setInverted(true);
        
        leftMotors = new SpeedControllerGroup(leftFrontMotor, leftBackMotor  );
        addChild("Left Motors",leftMotors);
        
        
        rightFrontMotor = new VictorSP(0);
        addChild("Right Front Motor",rightFrontMotor);
        rightFrontMotor.setInverted(true);
        
        rightBackMotor = new VictorSP(1);
        addChild("Right Back Motor",rightBackMotor);
        rightBackMotor.setInverted(true);
        
        rightMotors = new SpeedControllerGroup(rightFrontMotor, rightBackMotor  );
        addChild("Right Motors",rightMotors);
        
        
        axium = new DifferentialDrive(leftMotors, rightMotors);
        addChild("Axium",axium);
        axium.setSafetyEnabled(true);
        axium.setExpiration(0.1);
        axium.setMaxOutput(1.0);

        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop


    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

